using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WMS.Utility
{
    public class SD
    {
        public const string Role_SuperAdmin = "1";
        public const string Role_Tenant = "2";
        public const string Role_WarehouseAdmin = "3";

        public const string AutoGenerated = "Auto Generated";

        public const int FlagEnum_Active = 1;
        public const int FlagEnum_NonActive = 0;

        public const string ProductLvl_IKU = "IKU";
        public const string ProductLvl_SKU = "SKU";

        public const int FlagStorageCode_DSBLD = 0;
        public const int FlagStorageCode_AVAIL = 1;
        public const int FlagStorageCode_BOOKD = 2;
        public const int FlagStorageCode_USED = 3;


        public const string FlagDO_CNC = "CANCEL";
        public const string FlagDO_OPN = "Open";
        public const string FlagDO_DO = "DO";
        public const string FlagDO_AR = "AR";
        public const string FlagDO_NOAR = "NO-AR";
        public const string FlagDO_PUT = "PUT";

        public const string FlagDOProduct_Canceled = "Canceled";
        public const string FlagDOProduct_Open = "Open";
        public const string FlagDOProduct_Booked = "Booked";
        public const string FlagDOProduct_Arrived = "Arrived";
        public const string FlagDOProduct_NotArrived = "Not Arrived";
        public const string FlagDOProduct_Puted = "Puted";
        public const string FlagDOProduct_Sold = "Sold";

        public const int FlagItemProduct_CNCL = 0;
        public const int FlagItemProduct_OPEN = 1;
        public const int FlagItemProduct_BOOK = 2;
        public const int FlagItemProduct_ARVD = 3;
        public const int FlagItemProduct_PUTD = 4;
        public const int FlagItemProduct_SOLD = 5;
        public const int FlagItemProduct_PICK = 6;

        public const int FlagSerialNumber_Open = 1;
        public const int FlagSerialNumber_IN = 2;
        public const int FlagSerialNumber_OUT = 3;

        public const int FlagOpname_Open = 1;
        public const int FlagOpname_Done = 2;

        public const int FlagOpnamePro_Open = 1;
        public const int FlagOpnamePro_Done = 2;

        public const int FlagOpnameProStorage_Open = 1;
        public const int FlagOpnameProStorage_Done = 2;

        public const int SOType_Retrieval = 1;
        public const int SOType_Sales = 2;

        public const int FlagSO_Canceled = 0;
        public const int FlagSO_Open = 1;
        public const int FlagSO_Ordered = 2;
        public const int FlagSO_Picked = 3;
        public const int FlagSO_Staged = 4;
        public const int FlagSO_Packed = 5;
        public const int FlagSO_Dispatch = 6;

        public const int FlagSOProduct_Canceled = 0;
        public const int FlagSOProduct_Open = 1;
        public const int FlagSOProduct_Booked = 2;
        public const int FlagSOProduct_Picked = 3;
        public const int FlagSOProduct_Staged = 4;
        public const int FlagSOProduct_Packed = 5;
        public const int FlagSOProduct_Dispatch = 6;
    }
}
